indent_style = "Block"
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
comment_width = 80
wrap_comments = true
condense_wildcard_suffixes = true
# brace_style = "PreferSameLine"
trailing_comma = "Never"
# use_field_init_shorthand = true
max_width = 120